name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop
jobs:
    check-application:
      strategy:
        matrix:
          go_version: [1.14, 1.15]
          os: [ubuntu-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go_version }}
        - run: go test
        - run: go run math.go 
